CREATE PROCEDURE dbo.insere_cliente_livrariadb
AS
BEGIN
	MERGE LIVRARIADB.dbo.CLIENTE Destino
	USING (
		SELECT DISTINCT NOME_CLIENTE, CPF, TELEFONE_CLIENTE, EMAIL_CLIENTE
		FROM STAGE.dbo.MOVIMENTACAO_LIVROS
	) Origem ON (Destino.CPF = Origem.CPF)

	WHEN MATCHED THEN
		UPDATE
		SET NOME_CLIENTE = Origem.NOME_CLIENTE,
			TELEFONE = Origem.TELEFONE_CLIENTE,
			EMAIL = Origem.EMAIL_CLIENTE

	WHEN NOT MATCHED THEN
		INSERT (
			NOME_CLIENTE,
			CPF,
			TELEFONE,
			EMAIL
		)
		VALUES (
			Origem.NOME_CLIENTE,
			Origem.CPF,
			Origem.TELEFONE_CLIENTE,
			Origem.EMAIL_CLIENTE
		);
END