CREATE DATABASE STAGE;
GO

USE STAGE;
GO

create table MOVIMENTACAO_LIVROS (
    NOME_CLIENTE         VARCHAR(100) NULL,
    NUMERO_ENDERECO      INT NULL,
    COMPLEMENTO          VARCHAR(100) NULL,
    CEP                  VARCHAR(15) NULL,
    TIPO_ENDERECO        INT NULL,
    EMAIL_CLIENTE        VARCHAR(100) NULL,
    TELEFONE_CLIENTE     VARCHAR(20) NULL,
    CPF                  VARCHAR(14) NULL,
    NUMERO_NOTA_FISCAL   INT NULL,
    QUANTIDADE           INT NULL,
    VALOR_ITEM           DECIMAL(10,2) NULL,
    VALOR_TOTAL          DECIMAL(10,2) NULL,
    CONDICAO_PAGAMENTO   VARCHAR(100) NULL,
    TITULO               VARCHAR(200) NULL,
    AUTOR                VARCHAR(200) NULL,
    ID_LOJA              INT NULL,
    ID_ATENDENTE         INT NULL,
    DATA_VENDA           DATE NULL,
    DATA_PROCESSAMENTO   DATE NULL
);

