USE LIVRARIADB;

SELECT * FROM HISTORICO_RECEBIMENTO;

SELECT * FROM HISTORICO_DIVERGENTE;
SELECT * FROM STAGE.dbo.RECEBIMENTO; --criar essa tabela no LIVRARIADB com as fk
SELECT * FROM PROG_RECEBIMENTO;
SELECT * FROM NOTA_FISCAL;
SELECT * FROM TIPO_DESCONTO;

-- CRIANDO A PROCEADURE	

-- seleciona valores para os calculos, validações e inserções
SELECT * FROM TIPO_DESCONTO;
SELECT * FROM HISTORICO_RECEBIMENTO;
--====================================================
-- select da query
WITH #DADOS_CALCULADOS AS (
	SELECT
		PR.ID_PROG_RECEBIMENTO,
		PR.VAL_PARCELA AS VALOR_CALCULADO,
		RE.DATA_RECEBIMENTO,
		RE.VALOR_RECEBIDO AS VALOR_RECEBIDO,
		CAST(ROUND(ABS(1 - (RE.VALOR_RECEBIDO/PR.VAL_PARCELA)), 2) 
		AS DECIMAL(10,2)) AS PER_DESC,
	-- calculos
		CASE
			WHEN PR.VAL_PARCELA >= RE.VALOR_RECEBIDO THEN '1'
			WHEN PR.VAL_PARCELA < RE.VALOR_RECEBIDO THEN '0'
		END AS TIPO
	--
	FROM
		LIVRARIADB.dbo.PROG_RECEBIMENTO AS PR
	JOIN
		LIVRARIADB.dbo.NOTA_FISCAL AS NF 
		ON PR.ID_NF = NF.ID_NF
	JOIN STAGE.dbo.RECEBIMENTO AS RE
		ON NF.NUMERO_NOTA_FISCAL = RE.NUMERO_NF
)
--SELECT * FROM #DADOS_CALCULADOS
SELECT 
	DC.ID_PROG_RECEBIMENTO,
	TP.ID_TIPO_DESCONTO,
	DC.DATA_RECEBIMENTO,
	DC.VALOR_RECEBIDO
FROM #DADOS_CALCULADOS AS DC
JOIN
	TIPO_DESCONTO AS TP
	ON DC.TIPO = TP.TIPO
	AND DC.PER_DESC >= TP.PERCENT_MIN
	AND DC.PER_DESC < TP.PERCENT_MAX
	AND TP.STATUS = 1

--=============================================
-- consertando valores TIPO_DESCONTO
UPDATE TIPO_DESCONTO
SET PERCENT_MAX = 0.08
WHERE ID_TIPO_DESCONTO = 29

UPDATE TIPO_DESCONTO
SET PERCENT_MAX = 0.08
WHERE ID_TIPO_DESCONTO = 33

SELECT * FROM TIPO_DESCONTO;

-- planejando os calculos
-- Para obter o ID_TIPO_DESCONTO vamos calcular a porcentagem do dsoconto
-- aplicado e ver em qual intervalo ele cai, sevgundo a tabela TIPO_DESCONTO.
	-- Selecionar:
	--> PR.VALOR_CALCULADO
	--> PR.DATA_VENCIMENTO
	--> RE.VALOR_RECEBIDO
	--> fazer PR.VALOR_CALCULADO_RECEBIDO/RE.VALOR_CALCULADO_PARCELA =
	--	= PERCENT_DESCONTO
	--