USE STAGE;
GO

WITH pegar_data AS (
    SELECT
        NUMERO_NOTA_FISCAL,
        MIN(DATA_PROCESSAMENTO) AS MENOR_DATA,
        MAX(DATA_PROCESSAMENTO) AS MAIOR_DATA
    FROM 
        STAGE.dbo.MOVIMENTACAO_LIVROS
    GROUP BY 
        NUMERO_NOTA_FISCAL
)

SELECT
  CASE 
    WHEN MENOR_DATA != MAIOR_DATA THEN 'REJEITADO'
    ELSE 'OK'
  END
FROM pegar_data;

