USE LIVRARIADB;
GO
CREATE OR ALTER PROCEDURE dbo.atualiza_prog_recebimento
AS
BEGIN
	DECLARE db_cursor CURSOR FOR
		SELECT 
			HR.ID_PROG_RECEBIMENTO
		FROM 
			LIVRARIADB.dbo.HISTORICO_RECEBIMENTO AS HR
		JOIN LIVRARIADB.dbo.PROG_RECEBIMENTO AS PR
			ON HR.ID_PROG_RECEBIMENTO = PR.ID_PROG_RECEBIMENTO

	DECLARE @id_prog_recebimento AS INT;

	OPEN db_cursor
	FETCH NEXT FROM db_cursor INTO @id_prog_recebimento;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE LIVRARIADB.dbo.PROG_RECEBIMENTO
		SET PAGO = 1
		WHERE ID_PROG_RECEBIMENTO = @id_prog_recebimento;

	FETCH NEXT FROM db_cursor INTO @id_prog_recebimento;
	END
	CLOSE db_cursor;
	DEALLOCATE	db_cursor;
END