USE STAGE
GO

ALTER PROCEDURE dbo.carregar_validacao
AS
BEGIN

    INSERT INTO STAGE.dbo.VALIDACAO (NUMERO_NOTA_FISCAL, DATA_PROCESSAMENTO)
    SELECT DISTINCT  M.NUMERO_NOTA_FISCAL, M.DATA_PROCESSAMENTO
    FROM STAGE.dbo.MOVIMENTACAO_LIVROS AS M
    LEFT JOIN 
    STAGE.dbo.MOVIMENTACAO_LIVROS_REJEITADOS AS R 
    ON M.NUMERO_NOTA_FISCAL = R.NUMERO_NOTA_FISCAL_REJEITADOS 
    AND M.DATA_PROCESSAMENTO = R.DATA_PROCESSAMENTO_REJEITADOS
    WHERE R.NUMERO_NOTA_FISCAL_REJEITADOS IS NULL
    AND R.DATA_PROCESSAMENTO_REJEITADOS IS NULL
END

EXEC dbo.carregar_validacao;
