USE LIVRARIADB;
GO

CREATE PROCEDURE dbo.insere_item_venda_livrariadb
AS
BEGIN
	MERGE LIVRARIADB.dbo.ITEM_VENDA Destino
	USING (
		SELECT 
			LIV.ID_LIVRO,
			TRA.QUANTIDADE_TRATADOS AS QUANTIDADE
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS AS TRA
			JOIN LIVRARIADB.dbo.LIVRO AS LIV
				ON TRA.TITULO_TRATADOS = LIV.TITULO
	) Origem ON (Destino.ID_LIVRO = Origem.ID_LIVRO)
	WHEN MATCHED THEN
		UPDATE 
		SET ID_LIVRO = Origem.ID_LIVRO,
			QUANTIDADE = Origem.QUANTIDADE
	WHEN NOT MATCHED THEN
		INSERT(
			ID_LIVRO,
			QUANTIDADE
		)
		VALUES (
			Origem.ID_LIVRO,
			Origem.QUANTIDADE
		);
END