USE LIVRARIADB;
GO

CREATE PROCEDURE dbo.insere_endereco_livrariadb
AS
BEGIN
	MERGE LIVRARIADB.dbo.ENDERECOS_CLIENTES Destino
	USING (
		SELECT 
			CLI.ID_CLIENTE, ENDE.ID_TIPO_ENDERECO,
			TRA.CEP_TRATADOS AS CEP,
			TRA.NUMERO_ENDERECO_TRATADOS AS NUM,
			TRA.COMPLEMENTO_TRATADOS 
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS AS TRA
			JOIN LIVRARIADB.dbo.CLIENTE AS CLI 
				ON TRA.NOME_CLIENTE_TRATADOS = CLI.NOME_CLIENTE
			JOIN LIVRARIADB.dbo.TIPO_ENDERECO AS ENDE 
				ON TRA.TIPO_ENDERECO_TRATADOS = ENDE.SIGLA
	) Origem ON (Destino.CEP = Origem.CEP)

	WHEN MATCHED THEN
		UPDATE
		SET ID_CLIENTE = Origem.ID_CLIENTE,
			TIPO_ENDERECO = Origem.ID_TIPO_ENDERECO,
			CEP =  Origem.CEP,
			NUMERO =  Origem.NUM,
			COMPLEMENTO = Origem.COMPLEMENTO_TRATADOS
		
	WHEN NOT MATCHED THEN
		INSERT (
			ID_CLIENTE,
			TIPO_ENDERECO,
			CEP,
			NUMERO,
			COMPLEMENTO
		)
		VALUES (
			Origem.ID_CLIENTE,
			Origem.ID_TIPO_ENDERECO,
			Origem.CEP,
			Origem.NUM,
			Origem.COMPLEMENTO_TRATADOS
		);
END
-- OK