USE LIVRARIADB;
GO

CREATE OR ALTER PROCEDURE dbo.insere_cliente_livrariadb
AS
BEGIN
	MERGE LIVRARIADB.dbo.CLIENTE Destino
	USING (
		SELECT DISTINCT 
			NOME_CLIENTE_TRATADOS, CPF_TRATADOS, TELEFONE_CLIENTE_TRATADOS, EMAIL_CLIENTE_TRATADOS
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS
	) Origem ON (Destino.CPF = Origem.CPF_TRATADOS)

	WHEN MATCHED THEN
		UPDATE
		SET NOME_CLIENTE = Origem.NOME_CLIENTE_TRATADOS,
			TELEFONE = Origem.TELEFONE_CLIENTE_TRATADOS,
			EMAIL = Origem.EMAIL_CLIENTE_TRATADOS

	WHEN NOT MATCHED THEN
		INSERT (
			NOME_CLIENTE,
			CPF,
			TELEFONE,
			EMAIL
		)
		VALUES (
			Origem.NOME_CLIENTE_TRATADOS,
			Origem.CPF_TRATADOS,
			Origem.TELEFONE_CLIENTE_TRATADOS,
			Origem.EMAIL_CLIENTE_TRATADOS
		);
END
-- OK