-- 1 DEPOIS DE TODAS FEITAS DEPOIS DE 11/10/2025
USE LIVRARIADB;
GO
CREATE OR ALTER PROCEDURE dbo.insere_historico_recebimento
AS
BEGIN
    WITH DADOS_CALCULADOS AS (
        SELECT
            PR.ID_PROG_RECEBIMENTO,
            PR.VAL_PARCELA AS VALOR_CALCULADO,
            RE.DATA_RECEBIMENTO,
            RE.VALOR_PAGO AS VALOR_RECEBIDO,
            CAST(ROUND(ABS(1 - (RE.VALOR_PAGO / NULLIF(PR.VAL_PARCELA, 0))), 2) 
            AS DECIMAL(10,2)) AS PER_DESC,
        -- calculos
            CASE
                WHEN PR.VAL_PARCELA >= RE.VALOR_PAGO THEN '1'
                WHEN PR.VAL_PARCELA < RE.VALOR_PAGO THEN '0'
            END AS TIPO
        --
        FROM
            LIVRARIADB.dbo.PROG_RECEBIMENTO AS PR
        JOIN
            LIVRARIADB.dbo.NOTA_FISCAL AS NF 
            ON PR.ID_NF = NF.ID_NF
        JOIN STAGE.dbo.RECEBIMENTO AS RE
            ON NF.NUMERO_NOTA_FISCAL = RE.NUMERO_NOTA_FISCAL
            AND PR.NUM_PARCELA = RE.NUMERO_PARECLA
    )        
    INSERT INTO LIVRARIADB.dbo.HISTORICO_RECEBIMENTO
    (ID_PROG_RECEBIMENTO, ID_TIPO_DESCONTO, DATA_RECEBIMENTO, VALOR_RECEBIDO)
    SELECT 
        DC.ID_PROG_RECEBIMENTO,
        TP.ID_TIPO_DESCONTO,
        DC.DATA_RECEBIMENTO,
        DC.VALOR_RECEBIDO
    FROM DADOS_CALCULADOS AS DC
    JOIN
        LIVRARIADB.dbo.TIPO_DESCONTO AS TP
        ON DC.TIPO = TP.TIPO
        AND DC.PER_DESC >= TP.PERCENT_MIN
        AND DC.PER_DESC < TP.PERCENT_MAX + 0.01
        AND TP.STATUS = 1
    WHERE NOT EXISTS(
    SELECT 
        1
    FROM 
        LIVRARIADB.dbo.HISTORICO_RECEBIMENTO AS HR
    WHERE 
        DC.ID_PROG_RECEBIMENTO = HR.ID_PROG_RECEBIMENTO 
        AND TP.ID_TIPO_DESCONTO = HR.ID_TIPO_DESCONTO
        AND DC.DATA_RECEBIMENTO = HR.DATA_RECEBIMENTO
        AND DC.VALOR_RECEBIDO = HR.VALOR_RECEBIDO
	);
	-----------
	-- UPDATE PROG_RECEBIMENTO
    UPDATE PROG_RECEBIMENTO
	SET PAGO = 1
	WHERE ID_PROG_RECEBIMENTO IN (
		SELECT HR.ID_PROG_RECEBIMENTO 
		FROM HISTORICO_RECEBIMENTO AS HR
		JOIN PROG_RECEBIMENTO AS PG
		ON HR.ID_PROG_RECEBIMENTO = PG.ID_PROG_RECEBIMENTO
	)
END