USE LIVRARIADB;
GO

CREATE PROCEDURE dbo.insere_endereco_livrariadb
AS
BEGIN
	MERGE LIVRARIADB.dbo.ENDERECOS_CLIENTES Destino
	USING (
		SELECT DISTINCT 
			(SELECT ID_CLIENTE FROM LIVRARIADB.dbo.CLIENTE)AS ID_CLIENTE,
            (SELECT ID_TIPO_ENDERECO FROM LIVRARIADB.dbo.TIPO_ENDERECO) AS ID_TIPO_ENDERECO,
			(SELECT CEP FROM LIVRARIADB.dbo.CEP) AS CEP,
			NUMERO_ENDERECO_TRATADOS,
			COMPLEMENTO_TRATADOS
			
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS
	) Origem ON (Destino.NUMERO = Origem.NUMERO_ENDERECO_TRATADOS) -- mudar para CEP como ID quando concertar a tabela CEP do LIVRARIADB

	WHEN MATCHED THEN
		UPDATE
		SET ID_CLIENTE = Origem.ID_CLIENTE,
			ID_TIPO_ENDERECO = Origem.ID_TIPO_ENDERECO,
			CEP =  Origem.CEP,
			NUMERO =  Origem.NUMERO_ENDERECO_TRATADOS,
			COMPLEMENTO = Origem.COMPLEMENTO_TRATADOS
		
	WHEN NOT MATCHED THEN
		INSERT (
			ID_CLIENTE,
			ID_TIPO_ENDERECO,
			CEP,
			NUMERO,
			COMPLEMENTO
		)
		VALUES (
			Origem.ID_CLIENTE,
			Origem.ID_TIPO_ENDERECO,
			Origem.CEP,
			Origem.NUMERO_ENDERECO_TRATADOS,
			Origem.COMPLEMENTO_TRATADOS
		);
END

EXEC dbo.insere_endereco_livrariadb;


SELECT * FROM LIVRARIADB.dbo.ENDERECOS_CLIENTES;

SELECT * FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS;

SELECT  * FROM LIVRARIADB.dbo.CLIENTE;

SELECT  * FROM LIVRARIADB.dbo.TIPO_ENDERECO;

SELECT TOP 30 * FROM LIVRARIADB.dbo.CEP;

EXEC dbo.insere_tipo_endereco_livrariadb;


-- TABELA ENDERECO_CLIENTE do LIVRARIAEDB
/*
    v ID_ENDERECO_CLIENTE (PK) <- gerado Automaticamente
    v ID_CLIENTE (FK) <- tabela CLIENTE do LIVRARIADB
    v ID_TIPO_ENDERECO (FK) <- tabela TIPO_ENDERECO do LIVRARIADB
    v ID_CEP (FK) <- tabela CEP do LIVRARIADB
    v NUMERO (FK) <- tabela TRATADOS
    v COMPLEMENTO (FK) <- tabela TRATADOS
*/
