-- USANDO MERGE PARA TRATAR OS DADOS

--ERRADO
SELECT DISTINCT 
			(SELECT ID_CLIENTE FROM LIVRARIADB.dbo.CLIENTE) AS ID_CLIENTE,
            (SELECT ID_TIPO_ENDERECO FROM LIVRARIADB.dbo.TIPO_ENDERECO) AS ID_TIPO_ENDERECO,
			(SELECT TOP 100 CEP FROM LIVRARIADB.dbo.CEP) AS CEP,
			NUMERO_ENDERECO_TRATADOS,
			COMPLEMENTO_TRATADOS
			
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS
-- ==========================================================================================================
SELECT * FROM STAGE.dbo.TIPO_PAGAMENTO; -- TRATAR A COLUNA TIPO PARA JOIN NA CONDICAO DE PAGAMANETO TRATADO
SELECT CONDICAO_PAGAMENTO_TRATADOS FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS; 
--SELECT * FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS; 
-- ==========================================================================================================

SELECT CLI.ID_CLIENTE, ENDE.ID_TIPO_ENDERECO,TRA.CEP_TRATADOS, TRA.NUMERO_ENDERECO_TRATADOS, TRA.COMPLEMENTO_TRATADOS 
FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS AS TRA
JOIN LIVRARIADB.dbo.CLIENTE AS CLI ON TRA.NOME_CLIENTE_TRATADOS = CLI.NOME_CLIENTE
JOIN LIVRARIADB.dbo.TIPO_ENDERECO AS ENDE ON TRA.TIPO_ENDERECO_TRATADOS = ENDE.SIGLA

SELECT * FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS;
SELECT NOME_CLIENTE FROM LIVRARIADB.dbo.CLIENTE;
SELECT * FROM LIVRARIADB.dbo.TIPO_ENDERECO;

SELECT * FROM LIVRARIADB.dbo.ENDERECOS_CLIENTES;

USE LIVRARIADB
GO
EXEC sp_rename 'ENDERECOS_CLIENTES.ID_CEP', 'CEP', 'COLUMN';

-- ====================================================================
-- TESTANDO MERGE DA PROCEADSURE DE INSERCAO DO ENDERECO DOS CLIENTES

MERGE LIVRARIADB.dbo.ENDERECOS_CLIENTES Destino
	USING (
		SELECT 
			CLI.ID_CLIENTE, ENDE.ID_TIPO_ENDERECO,
			TRA.CEP_TRATADOS AS CEP,
			TRA.NUMERO_ENDERECO_TRATADOS AS NUM,
			TRA.COMPLEMENTO_TRATADOS 
		FROM 
			STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS AS TRA
			JOIN LIVRARIADB.dbo.CLIENTE AS CLI ON TRA.NOME_CLIENTE_TRATADOS = CLI.NOME_CLIENTE
			JOIN LIVRARIADB.dbo.TIPO_ENDERECO AS ENDE ON TRA.TIPO_ENDERECO_TRATADOS = ENDE.SIGLA
	) Origem ON (Destino.NUMERO = Origem.NUM) -- mudar para CEP como ID quando concertar a tabela CEP do LIVRARIADB

	WHEN MATCHED THEN
		UPDATE
		SET ID_CLIENTE = Origem.ID_CLIENTE,
			ID_TIPO_ENDERECO = Origem.ID_TIPO_ENDERECO,
			CEP =  Origem.CEP,
			NUMERO =  Origem.NUM,
			COMPLEMENTO = Origem.COMPLEMENTO_TRATADOS
		
	WHEN NOT MATCHED THEN
		INSERT (
			ID_CLIENTE,
			ID_TIPO_ENDERECO,
			CEP,
			NUMERO,
			COMPLEMENTO
		)
		VALUES (
			Origem.ID_CLIENTE,
			Origem.ID_TIPO_ENDERECO,
			Origem.CEP,
			Origem.NUM,
			Origem.COMPLEMENTO_TRATADOS
		);

-- TAREFAS:

-- CONSERTAR TABELA CEP E SUAS DEPENDENCIAS
-- obs: REMOVER COLUNA ID CEP E TORNAR CEP PK
-- ou
-- TRAZER O ID DO CEP NA TABELA MOVIMENTACAO_LIVROS_TRATADOS PARA FACILITAR JOINS
-- JOIN ID CEP NO COMEÇO DA PROCEADURE DE TRATAMENT

SELECT TOP 100 * FROM LIVRARIADB.dbo.CEP;

-- Dia 06/09 Arrumando

SELECT * FROM STAGE.dbo.TIPO_PAGAMENTO;
SELECT * FROM STAGE.dbo.MOVIMENTACAO_LIVROS_TRATADOS;
SELECT * FROM LIVRARIADB.dbo.TIPO_PAGAMENTO;
	